<?php

use Illuminate\Database\Seeder;
use Muserpol\Models\ProcedureDocument;
use Muserpol\Models\ProcedureModality;
use Muserpol\Models\ProcedureRequirement;

class UpdateRetFunReq24_11_2025 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // new documents
        $RES_A = ProcedureDocument::create(['name' => 'Resolución Administrativa de ingreso a la Disponibilidad (Letra “A”) en original o copia legalizada, emitido por el Comando General de la Policía Boliviana', 'shortened' => 'RES_A']);
        $RES_C = ProcedureDocument::create(['name' => 'Resolución Administrativa de ingreso a la Disponibilidad (Letra “C”) en original o copia legalizada, emitido por el Comando General de la Policía Boliviana', 'shortened' => 'RES_C']);
        $CN_T = ProcedureDocument::create(['name' => 'Certificado de nacimiento del titular en original y actualizado, emitido por el SERECI.', 'shortened' => 'CN_T']);

        // procedure_modalities ids
        $mod_retfun_jub = 3;
        $mod_retfun_inv = ProcedureModality::where('shortened', 'FRPS - I')->first()->id;
        $mod_retfun_fall = 4;
        $mod_retfun_retVol = 7;
        $mod_retfun_retFor = 5;

        $mod_da_tit = 62;
        $mod_da_fall = 63;
        $mod_da_retFor = ProcedureModality::where('shortened', 'DA - RF')->first()->id;
        $mod_da_retVol = ProcedureModality::where('shortened', 'DA - RV')->first()->id;

        $mod_pg_jub = ProcedureModality::where('shortened', 'PGA - JUB')->first()->id;
        $mod_pg_inv = 2;
        $mod_pg_fall = 1;

        // req list

        ProcedureRequirement::whereIn('procedure_modality_id', [$mod_retfun_jub, $mod_retfun_inv, $mod_retfun_fall, $mod_retfun_retVol, $mod_retfun_retFor, $mod_da_tit, $mod_da_fall, $mod_da_retFor, $mod_da_retVol, $mod_pg_jub, $mod_pg_inv, $mod_pg_fall])->delete();


        $req_retfun_jub = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 2, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 3, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 3, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 3, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 3, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 4, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 5, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 6, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_retfun_jub],

            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_retfun_jub],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_retfun_jub],
        ];
        foreach ($req_retfun_jub as $item) {
            $this->createOrRestore($item);
        }

        $req_retfun_inv = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 2, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 3, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 4, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 4, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 4, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 5, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 6, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 7, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_retfun_inv],

            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_retfun_inv],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_retfun_inv],
        ];
        foreach ($req_retfun_inv as $item) {
            $this->createOrRestore($item);
        }

        $req_retfun_fall = [
            ['number' => 1,  'procedure_document_id' => 3,   'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 1,  'procedure_document_id' => 346, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 2,  'procedure_document_id' => 9,   'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 3,  'procedure_document_id' => 11,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 3,  'procedure_document_id' => 33,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 4,  'procedure_document_id' => 12,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 4,  'procedure_document_id' => 13,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 4,  'procedure_document_id' => 44,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 4,  'procedure_document_id' => 115, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 5,  'procedure_document_id' => 15,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 6,  'procedure_document_id' => 16,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 6,  'procedure_document_id' => 17,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 6,  'procedure_document_id' => 25,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 7,  'procedure_document_id' => 7,   'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 8,  'procedure_document_id' => 231, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 9,  'procedure_document_id' => 272, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 10, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_retfun_fall],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_retfun_fall],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_retfun_fall],
        ];
        foreach ($req_retfun_fall as $item) {
            $this->createOrRestore($item);
        }

        $req_retfun_retVol = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_retfun_retVol],

            ['number' => 2, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 2, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 2, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_retfun_retVol],

            ['number' => 3, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_retfun_retVol],

            ['number' => 4, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_retfun_retVol],

            ['number' => 5, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_retfun_retVol],

            ['number' => 6, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 6, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 6, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 6, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 6, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 6, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_retfun_retVol],

            // number = 0 (incluye null)
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_retfun_retVol],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_retfun_retVol],
        ];
        foreach ($req_retfun_retVol as $item) {
            $this->createOrRestore($item);
        }

        $req_retfun_retFor = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_retfun_retFor],

            ['number' => 2, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 2, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_retfun_retFor],

            ['number' => 3, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_retfun_retFor],

            ['number' => 4, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_retfun_retFor],

            ['number' => 5, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_retfun_retFor],

            ['number' => 6, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 6, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 6, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 6, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 6, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 6, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_retfun_retFor],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_retfun_retFor],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_retfun_retFor],
        ];
        foreach ($req_retfun_retFor as $item) {
            $this->createOrRestore($item);
        }

        $req_da_tit = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_da_tit],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_da_tit],

            ['number' => 2, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 2, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_da_tit],

            ['number' => 3, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_da_tit],

            ['number' => 4, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_da_tit],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_da_tit],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_da_tit],
        ];
        foreach ($req_da_tit as $item) {
            $this->createOrRestore($item);
        }

        $req_da_fall = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_da_fall],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_da_fall],

            ['number' => 2, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 2, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_da_fall],

            ['number' => 3, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_da_fall],

            ['number' => 4, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_da_fall],

            ['number' => 5, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 5, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_da_fall],

            ['number' => 6, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 6, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 6, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_da_fall],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_da_fall],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_da_fall],
        ];
        foreach ($req_da_fall as $item) {
            $this->createOrRestore($item);
        }

        $req_da_retFor = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_da_retFor],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_da_retFor],

            ['number' => 2, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 2, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_da_retFor],

            ['number' => 3, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_da_retFor],

            ['number' => 4, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 4, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 4, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_da_retFor],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_da_retFor],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_da_retFor],
        ];
        foreach ($req_da_retFor as $item) {
            $this->createOrRestore($item);
        }

        $req_da_retVol = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_da_retVol],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_da_retVol],

            ['number' => 2, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 2, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_da_retVol],

            ['number' => 3, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_da_retVol],

            ['number' => 4, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 4, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 4, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 4, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_da_retVol],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_da_retVol],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_da_retVol],
        ];
        foreach ($req_da_retVol as $item) {
            $this->createOrRestore($item);
        }

        $req_pg_jub = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_pg_jub],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_pg_jub],

            ['number' => 2, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_pg_jub],

            ['number' => 3, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 3, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 3, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 3, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_pg_jub],

            ['number' => 4, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_pg_jub],
            ['number' => 5, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 6, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_pg_jub],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_pg_jub],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_pg_jub],
        ];
        foreach ($req_pg_jub as $item) {
            $this->createOrRestore($item);
        }

        $req_pg_inv = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_pg_inv],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_pg_inv],

            ['number' => 2, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 2, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_pg_inv],

            ['number' => 3, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_pg_inv],

            ['number' => 4, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 4, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 4, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_pg_inv],

            ['number' => 5, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_pg_inv],
            ['number' => 6, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 7, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_pg_inv],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_pg_inv],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_pg_inv],
        ];
        foreach ($req_pg_inv as $item) {
            $this->createOrRestore($item);
        }

        $req_pg_fall = [
            ['number' => 1, 'procedure_document_id' => 3,   'procedure_modality_id' => $mod_pg_fall],
            ['number' => 1, 'procedure_document_id' => 346, 'procedure_modality_id' => $mod_pg_fall],

            ['number' => 2, 'procedure_document_id' => 9,   'procedure_modality_id' => $mod_pg_fall],

            ['number' => 3, 'procedure_document_id' => 11,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 3, 'procedure_document_id' => 33,  'procedure_modality_id' => $mod_pg_fall],

            ['number' => 4, 'procedure_document_id' => 12,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 4, 'procedure_document_id' => 13,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 4, 'procedure_document_id' => 44,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 4, 'procedure_document_id' => 115, 'procedure_modality_id' => $mod_pg_fall],

            ['number' => 5, 'procedure_document_id' => 15,  'procedure_modality_id' => $mod_pg_fall],

            ['number' => 6, 'procedure_document_id' => 16,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 6, 'procedure_document_id' => 17,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 6, 'procedure_document_id' => 25,  'procedure_modality_id' => $mod_pg_fall],

            ['number' => 7, 'procedure_document_id' => 7,   'procedure_modality_id' => $mod_pg_fall],
            ['number' => 8, 'procedure_document_id' => 231, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 9, 'procedure_document_id' => 272, 'procedure_modality_id' => $mod_pg_fall],

            ['number' => 10, 'procedure_document_id' => 208, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 10, 'procedure_document_id' => 335, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 10, 'procedure_document_id' => $RES_A->id, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 10, 'procedure_document_id' => 325, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 10, 'procedure_document_id' => 338, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 10, 'procedure_document_id' => 324, 'procedure_modality_id' => $mod_pg_fall],

            // number = 0
            ['number' => 0, 'procedure_document_id' => 29,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 32,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 67,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 71,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 101, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 121, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 131, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 135, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 137, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 166, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 179, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 186, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 187, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 189, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 206, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 210, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 218, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 238, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 240, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 334, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 341, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 342, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 343, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 378, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 379, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 380, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 407, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 408, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 19,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 20,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 26,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 27,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 30,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 45,  'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 130, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 227, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 229, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 264, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 268, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 337, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 431, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 433, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 434, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 435, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => 436, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => $CN_T->id, 'procedure_modality_id' => $mod_pg_fall],
            ['number' => 0, 'procedure_document_id' => $RES_C->id, 'procedure_modality_id' => $mod_pg_fall],
        ];
        foreach ($req_pg_fall as $item) {
            $this->createOrRestore($item);
        }
    }

    protected function createOrRestore(array $data)
    {
        $record = ProcedureRequirement::withTrashed()
            ->where('procedure_document_id', $data['procedure_document_id'])
            ->where('procedure_modality_id', $data['procedure_modality_id'])
            ->where('number', $data['number'])
            ->first();

        if ($record) {
            if ($record->trashed()) {
                $record->restore();
            }

            return $record;
        }

        return ProcedureRequirement::create($data);
    }
}
